language: clojure
sudo: required
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update
  - git clone https://github.com/skyebook/FFmpeg.git
  - cd FFmpeg
  - git checkout release/3.0
  - ./configure --enable-static --enable-gpl --enable-nonfree --enable-gnutls --enable-libx264 --enable-pthreads
  - make
  - make install
  - which ffmpeg
  script: ffmpeg -h
